---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:year:month:day ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Andrew Herman | hippiefuturist"
keywords:    "aherman, Andrew Herman, hippiefuturist, polymath, art, technology, spirituality"
description: "Polymath with special interest in the nexus of art, technology and spirituality."
source_link: "https://aherman.github.io"
email: andrew.scott.herman@gmail.com
favicon:     "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: UA-96451400-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
